version: '3.5'

services:
  frontend:
    image: frontend
    build: .
    ports: 
      - 5000:5000
    command: npm start
  backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    command: npm start
    environment: 
      - REDIS=redis

  redis:
    image: redis
    expose: 
      - 6379
    ports: 
      - 6379:6379

