version: '3.5'

services:
  frontend:
    image: frontend
    build: .
    ports: 
      - 5000:5000
    command: npm start
    depends_on: 
      - backend

  backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    command: npm start
    environment: 
      - REDIS=redis
      - DB_USERNAME=username
      - DB_PASSWORD=example
      - DB_NAME=db
      - DB_HOST=db
    depends_on: 
      - db
      - redis

  redis:
    image: redis
    expose: 
      - 6379
    ports: 
      - 6379:6379

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
    expose: 
      - 5432
    ports: 
      - 5432:5432

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
     - backend
    

