version: '3.5'

services: 
  frontend:
    image: kurkkumopo_frontend
    build: .
    ports:
      - 3000:3000
  backend:
    image: kurkkumopo_backend
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./model:/src/model
    depends_on: 
      - training

  training:
    image: kurkkumopo_training
    build: .
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs